services:
  chatbot_ia:

    build:
      context: .
      dockerfile: Dockerfile

    container_name: chatbot_ia

    network_mode: host

    privileged: true

    stdin_open: true
    tty: true

    working_dir: /workspace

    command: bash

    devices:
      - "/dev/snd:/dev/snd"

    group_add:
      - audio

    environment:
      - DISPLAY=${DISPLAY}
      - XDG_RUNTIME_DIR=/run/user/1000
      - PULSE_SERVER=tcp:127.0.0.1:4713

    volumes:
      - ../:/workspace

      - /tmp/.X11-unix:/tmp/.X11-unix

      - /run/user/1000/pulse:/run/user/1000/pulse

      - /dev/snd:/dev/snd